local world = {
    objects = {
        heaven = {
            kind = "location",
            description = "little heaven",
            tags = { "heaven", "little heaven" },
            details = "Everything looks so peaceful here.",
            gossip = "It's where all the good adventurers go.",
            capacity = 9999,
            light = 100,
        },
        respawn = {
            kind = "passage",
            description = "a respawn portal",
            tags = { "portal", "respawn portal" },
            location = "heaven",
            destination = "field",
            prospect = "field",
            details = "Looks like a gateway into the unknown.",
            text_go = "A bright flash of light, and you are back in the field.",
            on_open = "isAlreadyOpen",
        },
        heavenEWNS = {
            kind = "passage",
            description = "nothing but peace and quiet",
            tags = { "east", "west", "north", "south" },
            location = "heaven",
            details = "You see nothing special.",
            contents = "You see",
            text_go = "In this dimension, there are no directions.",
            gossip = "It's just a compass direction.",
        },
        field = {
            kind = "location",
            description = "an open field",
            tags = { "field" },
            details = "The field is a nice and quiet place under a clear blue sky.",
            contents = "You see",
            gossip = "A lot of tourists go there.",
            capacity = 9999,
            light = 100,
        },
        cave = {
            kind = "location",
            description = "a little cave",
            tags = { "cave" },
            details = "The cave is just a cold, damp, rocky chamber.",
            contents = "You see",
            gossip = "It's dark in there; bring a lamp!",
            capacity = 9999,
        },
        silver = {
            kind = "item",
            description = "a silver coin",
            tags = { "silver", "coin", "silver coin" },
            location = "field",
            details = "The coin has an eagle on the obverse.",
            contents = "You see",
            gossip = "Money makes the world go round...",
            weight = 1,
        },
        gold = {
            kind = "item",
            description = "a gold coin",
            tags = { "gold", "coin", "gold coin" },
            location = "openBox",
            details = "The shiny coin seems to be a rare and priceless artefact.",
            contents = "You see",
            gossip = "Money makes the world go round...",
            weight = 1,
        },
        guard = {
            kind = "actor",
            description = "a burly guard",
            tags = { "guard", "burly guard" },
            location = "field",
            details = "The guard is a really big fellow.",
            contents = "He has",
            gossip = "Easy to bribe...",
            health = 100,
            impact = -1,
            capacity = 20,
        },
        player = {
            kind = "actor",
            description = "yourself",
            tags = { "yourself" },
            location = "field",
            details = "You would need a mirror to look at yourself.",
            contents = "You have",
            gossip = "You're not from around here, are you?",
            health = 100,
            capacity = 20,
            impact = -1,
        },
        intoCave = {
            kind = "passage",
            description = "a cave entrance to the east",
            tags = { "east", "entrance" },
            location = "field",
            destination = "cave",
            prospect = "cave",
            details = "The entrance is just a narrow opening in a small outcrop.",
            contents = "You see",
            text_go = "You walk into the cave.",
            condition = function(worldData, selfId)
                local guardHealth = engine.get_field("guard", "health")
                local silverLocation = engine.get_field("silver", "location")
                print('Silver Location: ' .. tostring(silverLocation))
                return true
                -- return guardHealth ~= nil and silverLocation ~= nil
                --     and (guardHealth == 0 or silverLocation == "guard")
            end,
            on_open = "isAlreadyOpen",
        },
        intoCaveBlocked = {
            kind = "passage",
            description = "a cave entrance to the east",
            tags = { "east", "entrance" },
            location = "field",
            prospect = "cave",
            details = "The entrance is just a narrow opening in a small outcrop.",
            contents = "You see",
            text_go = "The guard stops you from walking into the cave.",
            condition = function(worldData, selfId)
                local guardHealth = engine.get_field("guard", "health")
                local silverLocation = engine.get_field("silver", "location")
                return guardHealth ~= nil and silverLocation ~= nil
                    and guardHealth > 0
                    and silverLocation ~= "guard"
            end,
            on_open = "isAlreadyOpen",
        },
        exitCave = {
            kind = "passage",
            description = "an exit to the west",
            tags = { "west", "exit" },
            location = "cave",
            destination = "field",
            prospect = "field",
            details = "Sunlight pours in through an opening in the cave's wall.",
            contents = "You see",
            text_go = "You walk out of the cave.",
            on_open = "isAlreadyOpen",
        },
        wallField = {
            kind = "passage",
            description = "dense forest all around",
            tags = { "west", "north", "south", "forest" },
            location = "field",
            details = "The field is surrounded by trees and undergrowth.",
            contents = "You see",
            text_go = "Dense forest is blocking the way.",
            gossip = "You cannot go there, it is impenetrable.",
        },
        wallCave = {
            kind = "passage",
            description = "solid rock all around",
            tags = { "east", "north", "rock" },
            location = "cave",
            details = "Carved in stone is a secret password 'abccb'.",
            contents = "You see",
            text_go = "Solid rock is blocking the way.",
        },
        backroom = {
            kind = "location",
            description = "a backroom",
            tags = { "backroom" },
            details = "The room is dusty and messy.",
            contents = "You see",
            gossip = "There is something of value to be found there.",
            capacity = 9999,
        },
        wallBackroom = {
            kind = "passage",
            description = "solid rock all around",
            tags = { "east", "west", "south", "rock" },
            location = "backroom",
            details = "Trendy wallpaper covers the rock walls.",
            contents = "You see",
            text_go = "Solid rock is blocking the way.",
        },
        openDoorToBackroom = {
            kind = "passage",
            description = "an open door to the south",
            tags = { "south", "door", "doorway" },
            destination = "backroom",
            prospect = "backroom",
            details = "The door is open.",
            contents = "You see",
            text_go = "You walk through the door into a backroom.",
            on_open = "isAlreadyOpen",
            on_close = "toggleDoorToBackroom",
        },
        closedDoorToBackroom = {
            kind = "passage",
            description = "a closed door to the south",
            tags = { "south", "door", "doorway" },
            location = "cave",
            prospect = "backroom",
            details = "The door is closed.",
            contents = "You see",
            text_go = "The door is closed.",
            on_open = "toggleDoorToBackroom",
            on_close = "isAlreadyClosed",
        },
        openDoorToCave = {
            kind = "passage",
            description = "an open door to the north",
            tags = { "north", "door", "doorway" },
            destination = "cave",
            prospect = "cave",
            details = "The door is open.",
            contents = "You see",
            text_go = "You walk through the door into the cave.",
            on_open = "isAlreadyOpen",
            on_close = "toggleDoorToCave",
        },
        closedDoorToCave = {
            kind = "passage",
            description = "a closed door to the north",
            tags = { "north", "door", "doorway" },
            location = "backroom",
            prospect = "cave",
            details = "The door is closed.",
            contents = "You see",
            text_go = "The door is closed.",
            on_open = "toggleDoorToCave",
            on_close = "isAlreadyClosed",
        },
        openBox = {
            kind = "container",
            description = "a wooden box",
            tags = { "box", "wooden box" },
            details = "The box is open.",
            contents = "You see",
            gossip = "You need a key to open it.",
            weight = 5,
            capacity = 10,
            on_open = "isAlreadyOpen",
            on_close = "toggleBox",
            on_lock = "isStillOpen",
            on_unlock = "isAlreadyOpen",
        },
        closedBox = {
            kind = "container",
            description = "a wooden box",
            tags = { "box", "wooden box" },
            details = "The box is closed.",
            contents = "You see",
            weight = 5,
            on_open = "toggleBox",
            on_close = "isAlreadyClosed",
            on_lock = "toggleBoxLock",
            on_unlock = "isAlreadyUnlocked",
        },
        lockedBox = {
            kind = "container",
            description = "a wooden box",
            tags = { "box", "wooden box" },
            location = "backroom",
            details = "The box is closed.",
            contents = "You see",
            weight = 5,
            on_open = "isStillLocked",
            on_close = "isAlreadyClosed",
            on_lock = "isAlreadyLocked",
            on_unlock = "toggleBoxLock",
        },
        keyForBox = {
            kind = "item",
            description = "a tiny key",
            tags = { "key", "tiny key" },
            location = "cave",
            details = "The key is really small and shiny.",
            contents = "You see",
            gossip = "A small key opens a small lock.",
            weight = 1,
        },
        lampOff = {
            kind = "item",
            description = "a lamp",
            tags = { "lamp" },
            location = "field",
            details = "The lamp is off.",
            contents = "You see",
            gossip = "Essential in dark areas.",
            weight = 5,
        },
        lampOn = {
            kind = "item",
            description = "a lamp",
            tags = { "lamp" },
            details = "The lamp is on.",
            contents = "You see",
            weight = 5,
            light = 100,
        },
        club = {
            kind = "item",
            description = "a wooden club",
            tags = { "club", "wooden club" },
            location = "field",
            details = "Two feet of solid wood.",
            contents = "You see",
            weight = 5,
            impact = -2,
        },
        dagger = {
            kind = "item",
            description = "a dagger",
            tags = { "dagger" },
            location = "field",
            details = "The dagger is very sharp.",
            contents = "You see",
            weight = 7,
            impact = -5,
        },
    },
}

return world
